// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMerStoreProductSku = "mer_store_product_sku"

// MerStoreProductSku mapped from table <mer_store_product_sku>
type MerStoreProductSku struct {
	ProductSkuID int32    `gorm:"column:product_sku_id;type:int;primaryKey;autoIncrement:true" json:"product_sku_id"`
	ProductID    int32    `gorm:"column:product_id;type:int unsigned;not null" json:"product_id"`
	AttrName     *string  `gorm:"column:attr_name;type:varchar(255);comment:商品属性" json:"attr_name"`                // 商品属性
	Price        *float64 `gorm:"column:price;type:decimal(10,2) unsigned;default:0.00;comment:最低价格" json:"price"` // 最低价格
	Cost         *float64 `gorm:"column:cost;type:decimal(10,2);default:0.00;comment:成本价" json:"cost"`             // 成本价
	OtPrice      *float64 `gorm:"column:ot_price;type:decimal(10,2);default:0.00;comment:原价" json:"ot_price"`      // 原价
	Image        *string  `gorm:"column:image;type:varchar(255);comment:属性图片" json:"image"`                        // 属性图片
}

// TableName MerStoreProductSku's table name
func (*MerStoreProductSku) TableName() string {
	return TableNameMerStoreProductSku
}
