// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerMerchantAdmin = "mer_merchant_admin"

// MerMerchantAdmin 商户管理员表
type MerMerchantAdmin struct {
	MerchantAdminID int32      `gorm:"column:merchant_admin_id;type:smallint unsigned;primaryKey;autoIncrement:true;comment:商户管理员表ID" json:"merchant_admin_id"` // 商户管理员表ID
	MerID           int32      `gorm:"column:mer_id;type:int unsigned;not null;comment:商户ID(属于哪一个商户)" json:"mer_id"`                                            // 商户ID(属于哪一个商户)
	Account         string     `gorm:"column:account;type:varchar(32);not null;index:account,priority:1;comment:商户管理员账号" json:"account"`                        // 商户管理员账号
	Pwd             string     `gorm:"column:pwd;type:char(64);not null;comment:商户管理员密码" json:"pwd"`                                                            // 商户管理员密码
	RealName        string     `gorm:"column:real_name;type:varchar(16);not null;comment:商户管理员姓名" json:"real_name"`                                             // 商户管理员姓名
	Phone           *string    `gorm:"column:phone;type:varchar(13);index:phone,priority:1;comment:商户管理员手机号" json:"phone"`                                      // 商户管理员手机号
	LastIP          *string    `gorm:"column:last_ip;type:varchar(16);comment:商户管理员最后一次登录IP地址" json:"last_ip"`                                                  // 商户管理员最后一次登录IP地址
	LastTime        *time.Time `gorm:"column:last_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:商户管理员最后一次登录时间" json:"last_time"`                        // 商户管理员最后一次登录时间
	Roles           *string    `gorm:"column:roles;type:varchar(128)" json:"roles"`
	LoginCount      int32      `gorm:"column:login_count;type:int unsigned;not null;comment:商户管理员登录次数" json:"login_count"`                    // 商户管理员登录次数
	Level           int32      `gorm:"column:level;type:tinyint unsigned;not null;default:1;comment:商户管理员等级(管理员添加的为0, 商户添加的为1)" json:"level"` // 商户管理员等级(管理员添加的为0, 商户添加的为1)
	IsDel           int32      `gorm:"column:is_del;type:tinyint unsigned;not null;comment:是否删除" json:"is_del"`                               // 是否删除
	Status          int32      `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:是否有效 1有效 0无效" json:"status"`             // 是否有效 1有效 0无效
	CreateAt        time.Time  `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:商户管理员添加时间" json:"create_at"`  // 商户管理员添加时间
}

// TableName MerMerchantAdmin's table name
func (*MerMerchantAdmin) TableName() string {
	return TableNameMerMerchantAdmin
}
