// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerStoreCategory = "mer_store_category"

// MerStoreCategory 商品分类表
type MerStoreCategory struct {
	StoreCategoryID int32      `gorm:"column:store_category_id;type:mediumint;primaryKey;autoIncrement:true;comment:商品分类表ID" json:"store_category_id"` // 商品分类表ID
	CateName        string     `gorm:"column:cate_name;type:varchar(100);not null;comment:分类名称" json:"cate_name"`                                      // 分类名称
	Sort            int32      `gorm:"column:sort;type:mediumint;not null;index:sort,priority:1;comment:排序" json:"sort"`                               // 排序
	Pic             string     `gorm:"column:pic;type:varchar(128);not null;comment:图标" json:"pic"`                                                    // 图标
	Level           int32      `gorm:"column:level;type:int unsigned;not null;comment:等级" json:"level"`                                                // 等级
	MerID           *int32     `gorm:"column:mer_id;type:int unsigned;comment:商户id" json:"mer_id"`                                                     // 商户id
	CreateAt        *time.Time `gorm:"column:create_at;type:timestamp;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_at"`                        // 添加时间
}

// TableName MerStoreCategory's table name
func (*MerStoreCategory) TableName() string {
	return TableNameMerStoreCategory
}
