// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMerStoreProductContent = "mer_store_product_content"

// MerStoreProductContent 商品详情表
type MerStoreProductContent struct {
	ProductID int32  `gorm:"column:product_id;type:int unsigned;not null;index:product_id,priority:1;comment:商品id" json:"product_id"` // 商品id
	Content   string `gorm:"column:content;type:longtext;not null;comment:商品详情" json:"content"`                                       // 商品详情
}

// TableName MerStoreProductContent's table name
func (*MerStoreProductContent) TableName() string {
	return TableNameMerStoreProductContent
}
