// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerStoreProduct = "mer_store_product"

// MerStoreProduct 商品表
type MerStoreProduct struct {
	ProductID     int32     `gorm:"column:product_id;type:int unsigned;primaryKey;autoIncrement:true;comment:商品id" json:"product_id"`                            // 商品id
	MerID         int32     `gorm:"column:mer_id;type:int unsigned;not null;index:mer_id,priority:1;comment:商户Id" json:"mer_id"`                                 // 商户Id
	StoreName     string    `gorm:"column:store_name;type:varchar(128);not null;comment:商品名称" json:"store_name"`                                                 // 商品名称
	StoreInfo     string    `gorm:"column:store_info;type:varchar(256);not null;comment:商品简介" json:"store_info"`                                                 // 商品简介
	Keyword       string    `gorm:"column:keyword;type:varchar(128);not null;comment:关键字" json:"keyword"`                                                        // 关键字
	IsShow        int32     `gorm:"column:is_show;type:tinyint unsigned;not null;default:1;comment:商户 状态（0:未上架，1:上架，2:定时上架）" json:"is_show"`                     // 商户 状态（0:未上架，1:上架，2:定时上架）
	IsDel         int32     `gorm:"column:is_del;type:tinyint unsigned;not null;comment:是否删除" json:"is_del"`                                                     // 是否删除
	MerStatus     *bool     `gorm:"column:mer_status;type:tinyint(1);default:1;comment:商铺状态是否 1.正常 0. 非正常" json:"mer_status"`                                    // 商铺状态是否 1.正常 0. 非正常
	CateID        int32     `gorm:"column:cate_id;type:int;not null;index:cate_id,priority:1;comment:分类id" json:"cate_id"`                                       // 分类id
	UnitName      string    `gorm:"column:unit_name;type:varchar(16);not null;comment:单位名" json:"unit_name"`                                                     // 单位名
	Sort          int32     `gorm:"column:sort;type:smallint;not null;index:sort,priority:1;comment:排序" json:"sort"`                                             // 排序
	Sales         int32     `gorm:"column:sales;type:mediumint unsigned;not null;index:sales,priority:1;comment:销量" json:"sales"`                                // 销量
	Price         *float64  `gorm:"column:price;type:decimal(10,2) unsigned;default:0.00;comment:最低价格" json:"price"`                                             // 最低价格
	Cost          *float64  `gorm:"column:cost;type:decimal(10,2);default:0.00;comment:成本价" json:"cost"`                                                         // 成本价
	OtPrice       *float64  `gorm:"column:ot_price;type:decimal(10,2);default:0.00;comment:原价" json:"ot_price"`                                                  // 原价
	Stock         *int32    `gorm:"column:stock;type:int unsigned;comment:总库存" json:"stock"`                                                                     // 总库存
	IsGood        bool      `gorm:"column:is_good;type:tinyint(1);not null;comment:是否优品推荐" json:"is_good"`                                                       // 是否优品推荐
	ProductType   int32     `gorm:"column:product_type;type:tinyint unsigned;not null;comment:0.普通商品 1.秒杀商品,2.预售商品，3.助力商品，4.拼团商品" json:"product_type"`           // 0.普通商品 1.秒杀商品,2.预售商品，3.助力商品，4.拼团商品
	CreateAt      time.Time `gorm:"column:create_at;type:timestamp;not null;index:create_at,priority:1;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_at"` // 添加时间
	Image         string    `gorm:"column:image;type:varchar(256);not null;comment:商品图片" json:"image"`                                                           // 商品图片
	SliderImage   string    `gorm:"column:slider_image;type:varchar(2000);not null;comment:轮播图" json:"slider_image"`                                             // 轮播图
	Extend        string    `gorm:"column:extend;type:varchar(1000);not null;comment:扩展信息" json:"extend"`                                                        // 扩展信息
	RefundSwitch  *int32    `gorm:"column:refund_switch;type:tinyint;default:1;comment:是否支持退款" json:"refund_switch"`                                             // 是否支持退款
	Delete_       *int32    `gorm:"column:delete;type:tinyint" json:"delete"`
	AutoOnTime    *int32    `gorm:"column:auto_on_time;type:int;comment:自动上架时间" json:"auto_on_time"`                                               // 自动上架时间
	BarCodeNumber *string   `gorm:"column:bar_code_number;type:varchar(255);index:bar_code_number,priority:1;comment:商品条码" json:"bar_code_number"` // 商品条码
}

// TableName MerStoreProduct's table name
func (*MerStoreProduct) TableName() string {
	return TableNameMerStoreProduct
}
