// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMerMerchantCategory = "mer_merchant_category"

// MerMerchantCategory 商户分类表
type MerMerchantCategory struct {
	MerchantCategoryID int32     `gorm:"column:merchant_category_id;type:int unsigned;primaryKey;autoIncrement:true;comment:商户分类 id" json:"merchant_category_id"` // 商户分类 id
	CategoryName       string    `gorm:"column:category_name;type:varchar(32);not null;comment:商户分类名称" json:"category_name"`                                      // 商户分类名称
	CategoryScope      string    `gorm:"column:category_scope;type:varchar(255);not null;comment:经营范围" json:"category_scope"`                                     // 经营范围
	CreateAt           time.Time `gorm:"column:create_at;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:添加时间" json:"create_at"`                        // 添加时间
}

// TableName MerMerchantCategory's table name
func (*MerMerchantCategory) TableName() string {
	return TableNameMerMerchantCategory
}
