// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"merchant_api/internal/model"
)

func newMerMerchantAdmin(db *gorm.DB, opts ...gen.DOOption) merMerchantAdmin {
	_merMerchantAdmin := merMerchantAdmin{}

	_merMerchantAdmin.merMerchantAdminDo.UseDB(db, opts...)
	_merMerchantAdmin.merMerchantAdminDo.UseModel(&model.MerMerchantAdmin{})

	tableName := _merMerchantAdmin.merMerchantAdminDo.TableName()
	_merMerchantAdmin.ALL = field.NewAsterisk(tableName)
	_merMerchantAdmin.MerchantAdminID = field.NewInt32(tableName, "merchant_admin_id")
	_merMerchantAdmin.MerID = field.NewInt32(tableName, "mer_id")
	_merMerchantAdmin.Account = field.NewString(tableName, "account")
	_merMerchantAdmin.Pwd = field.NewString(tableName, "pwd")
	_merMerchantAdmin.RealName = field.NewString(tableName, "real_name")
	_merMerchantAdmin.Phone = field.NewString(tableName, "phone")
	_merMerchantAdmin.LastIP = field.NewString(tableName, "last_ip")
	_merMerchantAdmin.LastTime = field.NewTime(tableName, "last_time")
	_merMerchantAdmin.Roles = field.NewString(tableName, "roles")
	_merMerchantAdmin.LoginCount = field.NewInt32(tableName, "login_count")
	_merMerchantAdmin.Level = field.NewInt32(tableName, "level")
	_merMerchantAdmin.IsDel = field.NewInt32(tableName, "is_del")
	_merMerchantAdmin.Status = field.NewInt32(tableName, "status")
	_merMerchantAdmin.CreateAt = field.NewTime(tableName, "create_at")

	_merMerchantAdmin.fillFieldMap()

	return _merMerchantAdmin
}

// merMerchantAdmin 商户管理员表
type merMerchantAdmin struct {
	merMerchantAdminDo

	ALL             field.Asterisk
	MerchantAdminID field.Int32  // 商户管理员表ID
	MerID           field.Int32  // 商户ID(属于哪一个商户)
	Account         field.String // 商户管理员账号
	Pwd             field.String // 商户管理员密码
	RealName        field.String // 商户管理员姓名
	Phone           field.String // 商户管理员手机号
	LastIP          field.String // 商户管理员最后一次登录IP地址
	LastTime        field.Time   // 商户管理员最后一次登录时间
	Roles           field.String
	LoginCount      field.Int32 // 商户管理员登录次数
	Level           field.Int32 // 商户管理员等级(管理员添加的为0, 商户添加的为1)
	IsDel           field.Int32 // 是否删除
	Status          field.Int32 // 是否有效 1有效 0无效
	CreateAt        field.Time  // 商户管理员添加时间

	fieldMap map[string]field.Expr
}

func (m merMerchantAdmin) Table(newTableName string) *merMerchantAdmin {
	m.merMerchantAdminDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merMerchantAdmin) As(alias string) *merMerchantAdmin {
	m.merMerchantAdminDo.DO = *(m.merMerchantAdminDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merMerchantAdmin) updateTableName(table string) *merMerchantAdmin {
	m.ALL = field.NewAsterisk(table)
	m.MerchantAdminID = field.NewInt32(table, "merchant_admin_id")
	m.MerID = field.NewInt32(table, "mer_id")
	m.Account = field.NewString(table, "account")
	m.Pwd = field.NewString(table, "pwd")
	m.RealName = field.NewString(table, "real_name")
	m.Phone = field.NewString(table, "phone")
	m.LastIP = field.NewString(table, "last_ip")
	m.LastTime = field.NewTime(table, "last_time")
	m.Roles = field.NewString(table, "roles")
	m.LoginCount = field.NewInt32(table, "login_count")
	m.Level = field.NewInt32(table, "level")
	m.IsDel = field.NewInt32(table, "is_del")
	m.Status = field.NewInt32(table, "status")
	m.CreateAt = field.NewTime(table, "create_at")

	m.fillFieldMap()

	return m
}

func (m *merMerchantAdmin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merMerchantAdmin) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 14)
	m.fieldMap["merchant_admin_id"] = m.MerchantAdminID
	m.fieldMap["mer_id"] = m.MerID
	m.fieldMap["account"] = m.Account
	m.fieldMap["pwd"] = m.Pwd
	m.fieldMap["real_name"] = m.RealName
	m.fieldMap["phone"] = m.Phone
	m.fieldMap["last_ip"] = m.LastIP
	m.fieldMap["last_time"] = m.LastTime
	m.fieldMap["roles"] = m.Roles
	m.fieldMap["login_count"] = m.LoginCount
	m.fieldMap["level"] = m.Level
	m.fieldMap["is_del"] = m.IsDel
	m.fieldMap["status"] = m.Status
	m.fieldMap["create_at"] = m.CreateAt
}

func (m merMerchantAdmin) clone(db *gorm.DB) merMerchantAdmin {
	m.merMerchantAdminDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merMerchantAdmin) replaceDB(db *gorm.DB) merMerchantAdmin {
	m.merMerchantAdminDo.ReplaceDB(db)
	return m
}

type merMerchantAdminDo struct{ gen.DO }

type IMerMerchantAdminDo interface {
	gen.SubQuery
	Debug() IMerMerchantAdminDo
	WithContext(ctx context.Context) IMerMerchantAdminDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerMerchantAdminDo
	WriteDB() IMerMerchantAdminDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerMerchantAdminDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerMerchantAdminDo
	Not(conds ...gen.Condition) IMerMerchantAdminDo
	Or(conds ...gen.Condition) IMerMerchantAdminDo
	Select(conds ...field.Expr) IMerMerchantAdminDo
	Where(conds ...gen.Condition) IMerMerchantAdminDo
	Order(conds ...field.Expr) IMerMerchantAdminDo
	Distinct(cols ...field.Expr) IMerMerchantAdminDo
	Omit(cols ...field.Expr) IMerMerchantAdminDo
	Join(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo
	Group(cols ...field.Expr) IMerMerchantAdminDo
	Having(conds ...gen.Condition) IMerMerchantAdminDo
	Limit(limit int) IMerMerchantAdminDo
	Offset(offset int) IMerMerchantAdminDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerMerchantAdminDo
	Unscoped() IMerMerchantAdminDo
	Create(values ...*model.MerMerchantAdmin) error
	CreateInBatches(values []*model.MerMerchantAdmin, batchSize int) error
	Save(values ...*model.MerMerchantAdmin) error
	First() (*model.MerMerchantAdmin, error)
	Take() (*model.MerMerchantAdmin, error)
	Last() (*model.MerMerchantAdmin, error)
	Find() ([]*model.MerMerchantAdmin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerMerchantAdmin, err error)
	FindInBatches(result *[]*model.MerMerchantAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerMerchantAdmin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerMerchantAdminDo
	Assign(attrs ...field.AssignExpr) IMerMerchantAdminDo
	Joins(fields ...field.RelationField) IMerMerchantAdminDo
	Preload(fields ...field.RelationField) IMerMerchantAdminDo
	FirstOrInit() (*model.MerMerchantAdmin, error)
	FirstOrCreate() (*model.MerMerchantAdmin, error)
	FindByPage(offset int, limit int) (result []*model.MerMerchantAdmin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerMerchantAdminDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merMerchantAdminDo) Debug() IMerMerchantAdminDo {
	return m.withDO(m.DO.Debug())
}

func (m merMerchantAdminDo) WithContext(ctx context.Context) IMerMerchantAdminDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merMerchantAdminDo) ReadDB() IMerMerchantAdminDo {
	return m.Clauses(dbresolver.Read)
}

func (m merMerchantAdminDo) WriteDB() IMerMerchantAdminDo {
	return m.Clauses(dbresolver.Write)
}

func (m merMerchantAdminDo) Session(config *gorm.Session) IMerMerchantAdminDo {
	return m.withDO(m.DO.Session(config))
}

func (m merMerchantAdminDo) Clauses(conds ...clause.Expression) IMerMerchantAdminDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merMerchantAdminDo) Returning(value interface{}, columns ...string) IMerMerchantAdminDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merMerchantAdminDo) Not(conds ...gen.Condition) IMerMerchantAdminDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merMerchantAdminDo) Or(conds ...gen.Condition) IMerMerchantAdminDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merMerchantAdminDo) Select(conds ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merMerchantAdminDo) Where(conds ...gen.Condition) IMerMerchantAdminDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merMerchantAdminDo) Order(conds ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merMerchantAdminDo) Distinct(cols ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merMerchantAdminDo) Omit(cols ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merMerchantAdminDo) Join(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merMerchantAdminDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merMerchantAdminDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merMerchantAdminDo) Group(cols ...field.Expr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merMerchantAdminDo) Having(conds ...gen.Condition) IMerMerchantAdminDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merMerchantAdminDo) Limit(limit int) IMerMerchantAdminDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merMerchantAdminDo) Offset(offset int) IMerMerchantAdminDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merMerchantAdminDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerMerchantAdminDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merMerchantAdminDo) Unscoped() IMerMerchantAdminDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merMerchantAdminDo) Create(values ...*model.MerMerchantAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merMerchantAdminDo) CreateInBatches(values []*model.MerMerchantAdmin, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merMerchantAdminDo) Save(values ...*model.MerMerchantAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merMerchantAdminDo) First() (*model.MerMerchantAdmin, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantAdmin), nil
	}
}

func (m merMerchantAdminDo) Take() (*model.MerMerchantAdmin, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantAdmin), nil
	}
}

func (m merMerchantAdminDo) Last() (*model.MerMerchantAdmin, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantAdmin), nil
	}
}

func (m merMerchantAdminDo) Find() ([]*model.MerMerchantAdmin, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerMerchantAdmin), err
}

func (m merMerchantAdminDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerMerchantAdmin, err error) {
	buf := make([]*model.MerMerchantAdmin, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merMerchantAdminDo) FindInBatches(result *[]*model.MerMerchantAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merMerchantAdminDo) Attrs(attrs ...field.AssignExpr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merMerchantAdminDo) Assign(attrs ...field.AssignExpr) IMerMerchantAdminDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merMerchantAdminDo) Joins(fields ...field.RelationField) IMerMerchantAdminDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merMerchantAdminDo) Preload(fields ...field.RelationField) IMerMerchantAdminDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merMerchantAdminDo) FirstOrInit() (*model.MerMerchantAdmin, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantAdmin), nil
	}
}

func (m merMerchantAdminDo) FirstOrCreate() (*model.MerMerchantAdmin, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantAdmin), nil
	}
}

func (m merMerchantAdminDo) FindByPage(offset int, limit int) (result []*model.MerMerchantAdmin, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merMerchantAdminDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merMerchantAdminDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merMerchantAdminDo) Delete(models ...*model.MerMerchantAdmin) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merMerchantAdminDo) withDO(do gen.Dao) *merMerchantAdminDo {
	m.DO = *do.(*gen.DO)
	return m
}
