// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                      = new(Query)
	MerMerchantAdmin       *merMerchantAdmin
	MerMerchant            *merMerchant
	MerMerchantCategory    *merMerchantCategory
	MerStoreCategory       *merStoreCategory
	MerStoreProduct        *merStoreProduct
	MerStoreProductContent *merStoreProductContent
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	MerMerchantAdmin = &Q.MerMerchantAdmin
	MerMerchant = &Q.MerMerchant
	MerMerchantCategory = &Q.MerMerchantCategory
	MerStoreCategory = &Q.MerStoreCategory
	MerStoreProduct = &Q.MerStoreProduct
	MerStoreProductContent = &Q.MerStoreProductContent
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                     db,
		MerMerchantAdmin:       newMerMerchantAdmin(db, opts...),
		MerMerchant:            newMerMerchant(db, opts...),
		MerMerchantCategory:    newMerMerchantCategory(db, opts...),
		MerStoreCategory:       newMerStoreCategory(db, opts...),
		MerStoreProduct:        newMerStoreProduct(db, opts...),
		MerStoreProductContent: newMerStoreProductContent(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	MerMerchantAdmin       merMerchantAdmin
	MerMerchant            merMerchant
	MerMerchantCategory    merMerchantCategory
	MerStoreCategory       merStoreCategory
	MerStoreProduct        merStoreProduct
	MerStoreProductContent merStoreProductContent
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		MerMerchantAdmin:       q.MerMerchantAdmin.clone(db),
		MerMerchant:            q.MerMerchant.clone(db),
		MerMerchantCategory:    q.MerMerchantCategory.clone(db),
		MerStoreCategory:       q.MerStoreCategory.clone(db),
		MerStoreProduct:        q.MerStoreProduct.clone(db),
		MerStoreProductContent: q.MerStoreProductContent.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                     db,
		MerMerchantAdmin:       q.MerMerchantAdmin.replaceDB(db),
		MerMerchant:            q.MerMerchant.replaceDB(db),
		MerMerchantCategory:    q.MerMerchantCategory.replaceDB(db),
		MerStoreCategory:       q.MerStoreCategory.replaceDB(db),
		MerStoreProduct:        q.MerStoreProduct.replaceDB(db),
		MerStoreProductContent: q.MerStoreProductContent.replaceDB(db),
	}
}

type queryCtx struct {
	MerMerchantAdmin       IMerMerchantAdminDo
	MerMerchant            IMerMerchantDo
	MerMerchantCategory    IMerMerchantCategoryDo
	MerStoreCategory       IMerStoreCategoryDo
	MerStoreProduct        IMerStoreProductDo
	MerStoreProductContent IMerStoreProductContentDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		MerMerchantAdmin:       q.MerMerchantAdmin.WithContext(ctx),
		MerMerchant:            q.MerMerchant.WithContext(ctx),
		MerMerchantCategory:    q.MerMerchantCategory.WithContext(ctx),
		MerStoreCategory:       q.MerStoreCategory.WithContext(ctx),
		MerStoreProduct:        q.MerStoreProduct.WithContext(ctx),
		MerStoreProductContent: q.MerStoreProductContent.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
