// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"merchant_api/internal/model"
)

func newMerMerchantCategory(db *gorm.DB, opts ...gen.DOOption) merMerchantCategory {
	_merMerchantCategory := merMerchantCategory{}

	_merMerchantCategory.merMerchantCategoryDo.UseDB(db, opts...)
	_merMerchantCategory.merMerchantCategoryDo.UseModel(&model.MerMerchantCategory{})

	tableName := _merMerchantCategory.merMerchantCategoryDo.TableName()
	_merMerchantCategory.ALL = field.NewAsterisk(tableName)
	_merMerchantCategory.MerchantCategoryID = field.NewInt32(tableName, "merchant_category_id")
	_merMerchantCategory.CategoryName = field.NewString(tableName, "category_name")
	_merMerchantCategory.CategoryScope = field.NewString(tableName, "category_scope")
	_merMerchantCategory.CreateAt = field.NewTime(tableName, "create_at")

	_merMerchantCategory.fillFieldMap()

	return _merMerchantCategory
}

// merMerchantCategory 商户分类表
type merMerchantCategory struct {
	merMerchantCategoryDo

	ALL                field.Asterisk
	MerchantCategoryID field.Int32  // 商户分类 id
	CategoryName       field.String // 商户分类名称
	CategoryScope      field.String // 经营范围
	CreateAt           field.Time   // 添加时间

	fieldMap map[string]field.Expr
}

func (m merMerchantCategory) Table(newTableName string) *merMerchantCategory {
	m.merMerchantCategoryDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merMerchantCategory) As(alias string) *merMerchantCategory {
	m.merMerchantCategoryDo.DO = *(m.merMerchantCategoryDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merMerchantCategory) updateTableName(table string) *merMerchantCategory {
	m.ALL = field.NewAsterisk(table)
	m.MerchantCategoryID = field.NewInt32(table, "merchant_category_id")
	m.CategoryName = field.NewString(table, "category_name")
	m.CategoryScope = field.NewString(table, "category_scope")
	m.CreateAt = field.NewTime(table, "create_at")

	m.fillFieldMap()

	return m
}

func (m *merMerchantCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merMerchantCategory) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["merchant_category_id"] = m.MerchantCategoryID
	m.fieldMap["category_name"] = m.CategoryName
	m.fieldMap["category_scope"] = m.CategoryScope
	m.fieldMap["create_at"] = m.CreateAt
}

func (m merMerchantCategory) clone(db *gorm.DB) merMerchantCategory {
	m.merMerchantCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merMerchantCategory) replaceDB(db *gorm.DB) merMerchantCategory {
	m.merMerchantCategoryDo.ReplaceDB(db)
	return m
}

type merMerchantCategoryDo struct{ gen.DO }

type IMerMerchantCategoryDo interface {
	gen.SubQuery
	Debug() IMerMerchantCategoryDo
	WithContext(ctx context.Context) IMerMerchantCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerMerchantCategoryDo
	WriteDB() IMerMerchantCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerMerchantCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerMerchantCategoryDo
	Not(conds ...gen.Condition) IMerMerchantCategoryDo
	Or(conds ...gen.Condition) IMerMerchantCategoryDo
	Select(conds ...field.Expr) IMerMerchantCategoryDo
	Where(conds ...gen.Condition) IMerMerchantCategoryDo
	Order(conds ...field.Expr) IMerMerchantCategoryDo
	Distinct(cols ...field.Expr) IMerMerchantCategoryDo
	Omit(cols ...field.Expr) IMerMerchantCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo
	Group(cols ...field.Expr) IMerMerchantCategoryDo
	Having(conds ...gen.Condition) IMerMerchantCategoryDo
	Limit(limit int) IMerMerchantCategoryDo
	Offset(offset int) IMerMerchantCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerMerchantCategoryDo
	Unscoped() IMerMerchantCategoryDo
	Create(values ...*model.MerMerchantCategory) error
	CreateInBatches(values []*model.MerMerchantCategory, batchSize int) error
	Save(values ...*model.MerMerchantCategory) error
	First() (*model.MerMerchantCategory, error)
	Take() (*model.MerMerchantCategory, error)
	Last() (*model.MerMerchantCategory, error)
	Find() ([]*model.MerMerchantCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerMerchantCategory, err error)
	FindInBatches(result *[]*model.MerMerchantCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerMerchantCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerMerchantCategoryDo
	Assign(attrs ...field.AssignExpr) IMerMerchantCategoryDo
	Joins(fields ...field.RelationField) IMerMerchantCategoryDo
	Preload(fields ...field.RelationField) IMerMerchantCategoryDo
	FirstOrInit() (*model.MerMerchantCategory, error)
	FirstOrCreate() (*model.MerMerchantCategory, error)
	FindByPage(offset int, limit int) (result []*model.MerMerchantCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerMerchantCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merMerchantCategoryDo) Debug() IMerMerchantCategoryDo {
	return m.withDO(m.DO.Debug())
}

func (m merMerchantCategoryDo) WithContext(ctx context.Context) IMerMerchantCategoryDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merMerchantCategoryDo) ReadDB() IMerMerchantCategoryDo {
	return m.Clauses(dbresolver.Read)
}

func (m merMerchantCategoryDo) WriteDB() IMerMerchantCategoryDo {
	return m.Clauses(dbresolver.Write)
}

func (m merMerchantCategoryDo) Session(config *gorm.Session) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Session(config))
}

func (m merMerchantCategoryDo) Clauses(conds ...clause.Expression) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merMerchantCategoryDo) Returning(value interface{}, columns ...string) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merMerchantCategoryDo) Not(conds ...gen.Condition) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merMerchantCategoryDo) Or(conds ...gen.Condition) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merMerchantCategoryDo) Select(conds ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merMerchantCategoryDo) Where(conds ...gen.Condition) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merMerchantCategoryDo) Order(conds ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merMerchantCategoryDo) Distinct(cols ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merMerchantCategoryDo) Omit(cols ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merMerchantCategoryDo) Join(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merMerchantCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merMerchantCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merMerchantCategoryDo) Group(cols ...field.Expr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merMerchantCategoryDo) Having(conds ...gen.Condition) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merMerchantCategoryDo) Limit(limit int) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merMerchantCategoryDo) Offset(offset int) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merMerchantCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merMerchantCategoryDo) Unscoped() IMerMerchantCategoryDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merMerchantCategoryDo) Create(values ...*model.MerMerchantCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merMerchantCategoryDo) CreateInBatches(values []*model.MerMerchantCategory, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merMerchantCategoryDo) Save(values ...*model.MerMerchantCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merMerchantCategoryDo) First() (*model.MerMerchantCategory, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantCategory), nil
	}
}

func (m merMerchantCategoryDo) Take() (*model.MerMerchantCategory, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantCategory), nil
	}
}

func (m merMerchantCategoryDo) Last() (*model.MerMerchantCategory, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantCategory), nil
	}
}

func (m merMerchantCategoryDo) Find() ([]*model.MerMerchantCategory, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerMerchantCategory), err
}

func (m merMerchantCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerMerchantCategory, err error) {
	buf := make([]*model.MerMerchantCategory, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merMerchantCategoryDo) FindInBatches(result *[]*model.MerMerchantCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merMerchantCategoryDo) Attrs(attrs ...field.AssignExpr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merMerchantCategoryDo) Assign(attrs ...field.AssignExpr) IMerMerchantCategoryDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merMerchantCategoryDo) Joins(fields ...field.RelationField) IMerMerchantCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merMerchantCategoryDo) Preload(fields ...field.RelationField) IMerMerchantCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merMerchantCategoryDo) FirstOrInit() (*model.MerMerchantCategory, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantCategory), nil
	}
}

func (m merMerchantCategoryDo) FirstOrCreate() (*model.MerMerchantCategory, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerMerchantCategory), nil
	}
}

func (m merMerchantCategoryDo) FindByPage(offset int, limit int) (result []*model.MerMerchantCategory, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merMerchantCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merMerchantCategoryDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merMerchantCategoryDo) Delete(models ...*model.MerMerchantCategory) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merMerchantCategoryDo) withDO(do gen.Dao) *merMerchantCategoryDo {
	m.DO = *do.(*gen.DO)
	return m
}
