// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"merchant_api/internal/model"
)

func newMerStoreProductContent(db *gorm.DB, opts ...gen.DOOption) merStoreProductContent {
	_merStoreProductContent := merStoreProductContent{}

	_merStoreProductContent.merStoreProductContentDo.UseDB(db, opts...)
	_merStoreProductContent.merStoreProductContentDo.UseModel(&model.MerStoreProductContent{})

	tableName := _merStoreProductContent.merStoreProductContentDo.TableName()
	_merStoreProductContent.ALL = field.NewAsterisk(tableName)
	_merStoreProductContent.ProductID = field.NewInt32(tableName, "product_id")
	_merStoreProductContent.Content = field.NewString(tableName, "content")

	_merStoreProductContent.fillFieldMap()

	return _merStoreProductContent
}

// merStoreProductContent 商品详情表
type merStoreProductContent struct {
	merStoreProductContentDo

	ALL       field.Asterisk
	ProductID field.Int32  // 商品id
	Content   field.String // 商品详情

	fieldMap map[string]field.Expr
}

func (m merStoreProductContent) Table(newTableName string) *merStoreProductContent {
	m.merStoreProductContentDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merStoreProductContent) As(alias string) *merStoreProductContent {
	m.merStoreProductContentDo.DO = *(m.merStoreProductContentDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merStoreProductContent) updateTableName(table string) *merStoreProductContent {
	m.ALL = field.NewAsterisk(table)
	m.ProductID = field.NewInt32(table, "product_id")
	m.Content = field.NewString(table, "content")

	m.fillFieldMap()

	return m
}

func (m *merStoreProductContent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merStoreProductContent) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 2)
	m.fieldMap["product_id"] = m.ProductID
	m.fieldMap["content"] = m.Content
}

func (m merStoreProductContent) clone(db *gorm.DB) merStoreProductContent {
	m.merStoreProductContentDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merStoreProductContent) replaceDB(db *gorm.DB) merStoreProductContent {
	m.merStoreProductContentDo.ReplaceDB(db)
	return m
}

type merStoreProductContentDo struct{ gen.DO }

type IMerStoreProductContentDo interface {
	gen.SubQuery
	Debug() IMerStoreProductContentDo
	WithContext(ctx context.Context) IMerStoreProductContentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerStoreProductContentDo
	WriteDB() IMerStoreProductContentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerStoreProductContentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerStoreProductContentDo
	Not(conds ...gen.Condition) IMerStoreProductContentDo
	Or(conds ...gen.Condition) IMerStoreProductContentDo
	Select(conds ...field.Expr) IMerStoreProductContentDo
	Where(conds ...gen.Condition) IMerStoreProductContentDo
	Order(conds ...field.Expr) IMerStoreProductContentDo
	Distinct(cols ...field.Expr) IMerStoreProductContentDo
	Omit(cols ...field.Expr) IMerStoreProductContentDo
	Join(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo
	Group(cols ...field.Expr) IMerStoreProductContentDo
	Having(conds ...gen.Condition) IMerStoreProductContentDo
	Limit(limit int) IMerStoreProductContentDo
	Offset(offset int) IMerStoreProductContentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreProductContentDo
	Unscoped() IMerStoreProductContentDo
	Create(values ...*model.MerStoreProductContent) error
	CreateInBatches(values []*model.MerStoreProductContent, batchSize int) error
	Save(values ...*model.MerStoreProductContent) error
	First() (*model.MerStoreProductContent, error)
	Take() (*model.MerStoreProductContent, error)
	Last() (*model.MerStoreProductContent, error)
	Find() ([]*model.MerStoreProductContent, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreProductContent, err error)
	FindInBatches(result *[]*model.MerStoreProductContent, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerStoreProductContent) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerStoreProductContentDo
	Assign(attrs ...field.AssignExpr) IMerStoreProductContentDo
	Joins(fields ...field.RelationField) IMerStoreProductContentDo
	Preload(fields ...field.RelationField) IMerStoreProductContentDo
	FirstOrInit() (*model.MerStoreProductContent, error)
	FirstOrCreate() (*model.MerStoreProductContent, error)
	FindByPage(offset int, limit int) (result []*model.MerStoreProductContent, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerStoreProductContentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merStoreProductContentDo) Debug() IMerStoreProductContentDo {
	return m.withDO(m.DO.Debug())
}

func (m merStoreProductContentDo) WithContext(ctx context.Context) IMerStoreProductContentDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merStoreProductContentDo) ReadDB() IMerStoreProductContentDo {
	return m.Clauses(dbresolver.Read)
}

func (m merStoreProductContentDo) WriteDB() IMerStoreProductContentDo {
	return m.Clauses(dbresolver.Write)
}

func (m merStoreProductContentDo) Session(config *gorm.Session) IMerStoreProductContentDo {
	return m.withDO(m.DO.Session(config))
}

func (m merStoreProductContentDo) Clauses(conds ...clause.Expression) IMerStoreProductContentDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merStoreProductContentDo) Returning(value interface{}, columns ...string) IMerStoreProductContentDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merStoreProductContentDo) Not(conds ...gen.Condition) IMerStoreProductContentDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merStoreProductContentDo) Or(conds ...gen.Condition) IMerStoreProductContentDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merStoreProductContentDo) Select(conds ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merStoreProductContentDo) Where(conds ...gen.Condition) IMerStoreProductContentDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merStoreProductContentDo) Order(conds ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merStoreProductContentDo) Distinct(cols ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merStoreProductContentDo) Omit(cols ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merStoreProductContentDo) Join(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merStoreProductContentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merStoreProductContentDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merStoreProductContentDo) Group(cols ...field.Expr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merStoreProductContentDo) Having(conds ...gen.Condition) IMerStoreProductContentDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merStoreProductContentDo) Limit(limit int) IMerStoreProductContentDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merStoreProductContentDo) Offset(offset int) IMerStoreProductContentDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merStoreProductContentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreProductContentDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merStoreProductContentDo) Unscoped() IMerStoreProductContentDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merStoreProductContentDo) Create(values ...*model.MerStoreProductContent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merStoreProductContentDo) CreateInBatches(values []*model.MerStoreProductContent, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merStoreProductContentDo) Save(values ...*model.MerStoreProductContent) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merStoreProductContentDo) First() (*model.MerStoreProductContent, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductContent), nil
	}
}

func (m merStoreProductContentDo) Take() (*model.MerStoreProductContent, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductContent), nil
	}
}

func (m merStoreProductContentDo) Last() (*model.MerStoreProductContent, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductContent), nil
	}
}

func (m merStoreProductContentDo) Find() ([]*model.MerStoreProductContent, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerStoreProductContent), err
}

func (m merStoreProductContentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreProductContent, err error) {
	buf := make([]*model.MerStoreProductContent, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merStoreProductContentDo) FindInBatches(result *[]*model.MerStoreProductContent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merStoreProductContentDo) Attrs(attrs ...field.AssignExpr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merStoreProductContentDo) Assign(attrs ...field.AssignExpr) IMerStoreProductContentDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merStoreProductContentDo) Joins(fields ...field.RelationField) IMerStoreProductContentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merStoreProductContentDo) Preload(fields ...field.RelationField) IMerStoreProductContentDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merStoreProductContentDo) FirstOrInit() (*model.MerStoreProductContent, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductContent), nil
	}
}

func (m merStoreProductContentDo) FirstOrCreate() (*model.MerStoreProductContent, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductContent), nil
	}
}

func (m merStoreProductContentDo) FindByPage(offset int, limit int) (result []*model.MerStoreProductContent, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merStoreProductContentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merStoreProductContentDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merStoreProductContentDo) Delete(models ...*model.MerStoreProductContent) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merStoreProductContentDo) withDO(do gen.Dao) *merStoreProductContentDo {
	m.DO = *do.(*gen.DO)
	return m
}
