// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"merchant_api/internal/model"
)

func newMerStoreCategory(db *gorm.DB, opts ...gen.DOOption) merStoreCategory {
	_merStoreCategory := merStoreCategory{}

	_merStoreCategory.merStoreCategoryDo.UseDB(db, opts...)
	_merStoreCategory.merStoreCategoryDo.UseModel(&model.MerStoreCategory{})

	tableName := _merStoreCategory.merStoreCategoryDo.TableName()
	_merStoreCategory.ALL = field.NewAsterisk(tableName)
	_merStoreCategory.StoreCategoryID = field.NewInt32(tableName, "store_category_id")
	_merStoreCategory.CateName = field.NewString(tableName, "cate_name")
	_merStoreCategory.Sort = field.NewInt32(tableName, "sort")
	_merStoreCategory.Pic = field.NewString(tableName, "pic")
	_merStoreCategory.Level = field.NewInt32(tableName, "level")
	_merStoreCategory.MerID = field.NewInt32(tableName, "mer_id")
	_merStoreCategory.CreateAt = field.NewTime(tableName, "create_at")

	_merStoreCategory.fillFieldMap()

	return _merStoreCategory
}

// merStoreCategory 商品分类表
type merStoreCategory struct {
	merStoreCategoryDo

	ALL             field.Asterisk
	StoreCategoryID field.Int32  // 商品分类表ID
	CateName        field.String // 分类名称
	Sort            field.Int32  // 排序
	Pic             field.String // 图标
	Level           field.Int32  // 等级
	MerID           field.Int32  // 商户id
	CreateAt        field.Time   // 添加时间

	fieldMap map[string]field.Expr
}

func (m merStoreCategory) Table(newTableName string) *merStoreCategory {
	m.merStoreCategoryDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merStoreCategory) As(alias string) *merStoreCategory {
	m.merStoreCategoryDo.DO = *(m.merStoreCategoryDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merStoreCategory) updateTableName(table string) *merStoreCategory {
	m.ALL = field.NewAsterisk(table)
	m.StoreCategoryID = field.NewInt32(table, "store_category_id")
	m.CateName = field.NewString(table, "cate_name")
	m.Sort = field.NewInt32(table, "sort")
	m.Pic = field.NewString(table, "pic")
	m.Level = field.NewInt32(table, "level")
	m.MerID = field.NewInt32(table, "mer_id")
	m.CreateAt = field.NewTime(table, "create_at")

	m.fillFieldMap()

	return m
}

func (m *merStoreCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merStoreCategory) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["store_category_id"] = m.StoreCategoryID
	m.fieldMap["cate_name"] = m.CateName
	m.fieldMap["sort"] = m.Sort
	m.fieldMap["pic"] = m.Pic
	m.fieldMap["level"] = m.Level
	m.fieldMap["mer_id"] = m.MerID
	m.fieldMap["create_at"] = m.CreateAt
}

func (m merStoreCategory) clone(db *gorm.DB) merStoreCategory {
	m.merStoreCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merStoreCategory) replaceDB(db *gorm.DB) merStoreCategory {
	m.merStoreCategoryDo.ReplaceDB(db)
	return m
}

type merStoreCategoryDo struct{ gen.DO }

type IMerStoreCategoryDo interface {
	gen.SubQuery
	Debug() IMerStoreCategoryDo
	WithContext(ctx context.Context) IMerStoreCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerStoreCategoryDo
	WriteDB() IMerStoreCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerStoreCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerStoreCategoryDo
	Not(conds ...gen.Condition) IMerStoreCategoryDo
	Or(conds ...gen.Condition) IMerStoreCategoryDo
	Select(conds ...field.Expr) IMerStoreCategoryDo
	Where(conds ...gen.Condition) IMerStoreCategoryDo
	Order(conds ...field.Expr) IMerStoreCategoryDo
	Distinct(cols ...field.Expr) IMerStoreCategoryDo
	Omit(cols ...field.Expr) IMerStoreCategoryDo
	Join(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo
	Group(cols ...field.Expr) IMerStoreCategoryDo
	Having(conds ...gen.Condition) IMerStoreCategoryDo
	Limit(limit int) IMerStoreCategoryDo
	Offset(offset int) IMerStoreCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreCategoryDo
	Unscoped() IMerStoreCategoryDo
	Create(values ...*model.MerStoreCategory) error
	CreateInBatches(values []*model.MerStoreCategory, batchSize int) error
	Save(values ...*model.MerStoreCategory) error
	First() (*model.MerStoreCategory, error)
	Take() (*model.MerStoreCategory, error)
	Last() (*model.MerStoreCategory, error)
	Find() ([]*model.MerStoreCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreCategory, err error)
	FindInBatches(result *[]*model.MerStoreCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerStoreCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerStoreCategoryDo
	Assign(attrs ...field.AssignExpr) IMerStoreCategoryDo
	Joins(fields ...field.RelationField) IMerStoreCategoryDo
	Preload(fields ...field.RelationField) IMerStoreCategoryDo
	FirstOrInit() (*model.MerStoreCategory, error)
	FirstOrCreate() (*model.MerStoreCategory, error)
	FindByPage(offset int, limit int) (result []*model.MerStoreCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerStoreCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merStoreCategoryDo) Debug() IMerStoreCategoryDo {
	return m.withDO(m.DO.Debug())
}

func (m merStoreCategoryDo) WithContext(ctx context.Context) IMerStoreCategoryDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merStoreCategoryDo) ReadDB() IMerStoreCategoryDo {
	return m.Clauses(dbresolver.Read)
}

func (m merStoreCategoryDo) WriteDB() IMerStoreCategoryDo {
	return m.Clauses(dbresolver.Write)
}

func (m merStoreCategoryDo) Session(config *gorm.Session) IMerStoreCategoryDo {
	return m.withDO(m.DO.Session(config))
}

func (m merStoreCategoryDo) Clauses(conds ...clause.Expression) IMerStoreCategoryDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merStoreCategoryDo) Returning(value interface{}, columns ...string) IMerStoreCategoryDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merStoreCategoryDo) Not(conds ...gen.Condition) IMerStoreCategoryDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merStoreCategoryDo) Or(conds ...gen.Condition) IMerStoreCategoryDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merStoreCategoryDo) Select(conds ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merStoreCategoryDo) Where(conds ...gen.Condition) IMerStoreCategoryDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merStoreCategoryDo) Order(conds ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merStoreCategoryDo) Distinct(cols ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merStoreCategoryDo) Omit(cols ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merStoreCategoryDo) Join(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merStoreCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merStoreCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merStoreCategoryDo) Group(cols ...field.Expr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merStoreCategoryDo) Having(conds ...gen.Condition) IMerStoreCategoryDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merStoreCategoryDo) Limit(limit int) IMerStoreCategoryDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merStoreCategoryDo) Offset(offset int) IMerStoreCategoryDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merStoreCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreCategoryDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merStoreCategoryDo) Unscoped() IMerStoreCategoryDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merStoreCategoryDo) Create(values ...*model.MerStoreCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merStoreCategoryDo) CreateInBatches(values []*model.MerStoreCategory, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merStoreCategoryDo) Save(values ...*model.MerStoreCategory) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merStoreCategoryDo) First() (*model.MerStoreCategory, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreCategory), nil
	}
}

func (m merStoreCategoryDo) Take() (*model.MerStoreCategory, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreCategory), nil
	}
}

func (m merStoreCategoryDo) Last() (*model.MerStoreCategory, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreCategory), nil
	}
}

func (m merStoreCategoryDo) Find() ([]*model.MerStoreCategory, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerStoreCategory), err
}

func (m merStoreCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreCategory, err error) {
	buf := make([]*model.MerStoreCategory, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merStoreCategoryDo) FindInBatches(result *[]*model.MerStoreCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merStoreCategoryDo) Attrs(attrs ...field.AssignExpr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merStoreCategoryDo) Assign(attrs ...field.AssignExpr) IMerStoreCategoryDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merStoreCategoryDo) Joins(fields ...field.RelationField) IMerStoreCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merStoreCategoryDo) Preload(fields ...field.RelationField) IMerStoreCategoryDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merStoreCategoryDo) FirstOrInit() (*model.MerStoreCategory, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreCategory), nil
	}
}

func (m merStoreCategoryDo) FirstOrCreate() (*model.MerStoreCategory, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreCategory), nil
	}
}

func (m merStoreCategoryDo) FindByPage(offset int, limit int) (result []*model.MerStoreCategory, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merStoreCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merStoreCategoryDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merStoreCategoryDo) Delete(models ...*model.MerStoreCategory) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merStoreCategoryDo) withDO(do gen.Dao) *merStoreCategoryDo {
	m.DO = *do.(*gen.DO)
	return m
}
