// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"merchant_api/internal/model"
)

func newMerStoreProductSku(db *gorm.DB, opts ...gen.DOOption) merStoreProductSku {
	_merStoreProductSku := merStoreProductSku{}

	_merStoreProductSku.merStoreProductSkuDo.UseDB(db, opts...)
	_merStoreProductSku.merStoreProductSkuDo.UseModel(&model.MerStoreProductSku{})

	tableName := _merStoreProductSku.merStoreProductSkuDo.TableName()
	_merStoreProductSku.ALL = field.NewAsterisk(tableName)
	_merStoreProductSku.ProductSkuID = field.NewInt32(tableName, "product_sku_id")
	_merStoreProductSku.ProductID = field.NewInt32(tableName, "product_id")
	_merStoreProductSku.AttrName = field.NewString(tableName, "attr_name")
	_merStoreProductSku.Price = field.NewFloat64(tableName, "price")
	_merStoreProductSku.Cost = field.NewFloat64(tableName, "cost")
	_merStoreProductSku.OtPrice = field.NewFloat64(tableName, "ot_price")

	_merStoreProductSku.fillFieldMap()

	return _merStoreProductSku
}

type merStoreProductSku struct {
	merStoreProductSkuDo

	ALL          field.Asterisk
	ProductSkuID field.Int32
	ProductID    field.Int32
	AttrName     field.String  // 商品属性
	Price        field.Float64 // 最低价格
	Cost         field.Float64 // 成本价
	OtPrice      field.Float64 // 原价

	fieldMap map[string]field.Expr
}

func (m merStoreProductSku) Table(newTableName string) *merStoreProductSku {
	m.merStoreProductSkuDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m merStoreProductSku) As(alias string) *merStoreProductSku {
	m.merStoreProductSkuDo.DO = *(m.merStoreProductSkuDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *merStoreProductSku) updateTableName(table string) *merStoreProductSku {
	m.ALL = field.NewAsterisk(table)
	m.ProductSkuID = field.NewInt32(table, "product_sku_id")
	m.ProductID = field.NewInt32(table, "product_id")
	m.AttrName = field.NewString(table, "attr_name")
	m.Price = field.NewFloat64(table, "price")
	m.Cost = field.NewFloat64(table, "cost")
	m.OtPrice = field.NewFloat64(table, "ot_price")

	m.fillFieldMap()

	return m
}

func (m *merStoreProductSku) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *merStoreProductSku) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 6)
	m.fieldMap["product_sku_id"] = m.ProductSkuID
	m.fieldMap["product_id"] = m.ProductID
	m.fieldMap["attr_name"] = m.AttrName
	m.fieldMap["price"] = m.Price
	m.fieldMap["cost"] = m.Cost
	m.fieldMap["ot_price"] = m.OtPrice
}

func (m merStoreProductSku) clone(db *gorm.DB) merStoreProductSku {
	m.merStoreProductSkuDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m merStoreProductSku) replaceDB(db *gorm.DB) merStoreProductSku {
	m.merStoreProductSkuDo.ReplaceDB(db)
	return m
}

type merStoreProductSkuDo struct{ gen.DO }

type IMerStoreProductSkuDo interface {
	gen.SubQuery
	Debug() IMerStoreProductSkuDo
	WithContext(ctx context.Context) IMerStoreProductSkuDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMerStoreProductSkuDo
	WriteDB() IMerStoreProductSkuDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMerStoreProductSkuDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMerStoreProductSkuDo
	Not(conds ...gen.Condition) IMerStoreProductSkuDo
	Or(conds ...gen.Condition) IMerStoreProductSkuDo
	Select(conds ...field.Expr) IMerStoreProductSkuDo
	Where(conds ...gen.Condition) IMerStoreProductSkuDo
	Order(conds ...field.Expr) IMerStoreProductSkuDo
	Distinct(cols ...field.Expr) IMerStoreProductSkuDo
	Omit(cols ...field.Expr) IMerStoreProductSkuDo
	Join(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo
	Group(cols ...field.Expr) IMerStoreProductSkuDo
	Having(conds ...gen.Condition) IMerStoreProductSkuDo
	Limit(limit int) IMerStoreProductSkuDo
	Offset(offset int) IMerStoreProductSkuDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreProductSkuDo
	Unscoped() IMerStoreProductSkuDo
	Create(values ...*model.MerStoreProductSku) error
	CreateInBatches(values []*model.MerStoreProductSku, batchSize int) error
	Save(values ...*model.MerStoreProductSku) error
	First() (*model.MerStoreProductSku, error)
	Take() (*model.MerStoreProductSku, error)
	Last() (*model.MerStoreProductSku, error)
	Find() ([]*model.MerStoreProductSku, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreProductSku, err error)
	FindInBatches(result *[]*model.MerStoreProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MerStoreProductSku) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMerStoreProductSkuDo
	Assign(attrs ...field.AssignExpr) IMerStoreProductSkuDo
	Joins(fields ...field.RelationField) IMerStoreProductSkuDo
	Preload(fields ...field.RelationField) IMerStoreProductSkuDo
	FirstOrInit() (*model.MerStoreProductSku, error)
	FirstOrCreate() (*model.MerStoreProductSku, error)
	FindByPage(offset int, limit int) (result []*model.MerStoreProductSku, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMerStoreProductSkuDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m merStoreProductSkuDo) Debug() IMerStoreProductSkuDo {
	return m.withDO(m.DO.Debug())
}

func (m merStoreProductSkuDo) WithContext(ctx context.Context) IMerStoreProductSkuDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m merStoreProductSkuDo) ReadDB() IMerStoreProductSkuDo {
	return m.Clauses(dbresolver.Read)
}

func (m merStoreProductSkuDo) WriteDB() IMerStoreProductSkuDo {
	return m.Clauses(dbresolver.Write)
}

func (m merStoreProductSkuDo) Session(config *gorm.Session) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Session(config))
}

func (m merStoreProductSkuDo) Clauses(conds ...clause.Expression) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m merStoreProductSkuDo) Returning(value interface{}, columns ...string) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m merStoreProductSkuDo) Not(conds ...gen.Condition) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m merStoreProductSkuDo) Or(conds ...gen.Condition) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m merStoreProductSkuDo) Select(conds ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m merStoreProductSkuDo) Where(conds ...gen.Condition) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m merStoreProductSkuDo) Order(conds ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m merStoreProductSkuDo) Distinct(cols ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m merStoreProductSkuDo) Omit(cols ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m merStoreProductSkuDo) Join(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m merStoreProductSkuDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m merStoreProductSkuDo) RightJoin(table schema.Tabler, on ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m merStoreProductSkuDo) Group(cols ...field.Expr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m merStoreProductSkuDo) Having(conds ...gen.Condition) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m merStoreProductSkuDo) Limit(limit int) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m merStoreProductSkuDo) Offset(offset int) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m merStoreProductSkuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m merStoreProductSkuDo) Unscoped() IMerStoreProductSkuDo {
	return m.withDO(m.DO.Unscoped())
}

func (m merStoreProductSkuDo) Create(values ...*model.MerStoreProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m merStoreProductSkuDo) CreateInBatches(values []*model.MerStoreProductSku, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m merStoreProductSkuDo) Save(values ...*model.MerStoreProductSku) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m merStoreProductSkuDo) First() (*model.MerStoreProductSku, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductSku), nil
	}
}

func (m merStoreProductSkuDo) Take() (*model.MerStoreProductSku, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductSku), nil
	}
}

func (m merStoreProductSkuDo) Last() (*model.MerStoreProductSku, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductSku), nil
	}
}

func (m merStoreProductSkuDo) Find() ([]*model.MerStoreProductSku, error) {
	result, err := m.DO.Find()
	return result.([]*model.MerStoreProductSku), err
}

func (m merStoreProductSkuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MerStoreProductSku, err error) {
	buf := make([]*model.MerStoreProductSku, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m merStoreProductSkuDo) FindInBatches(result *[]*model.MerStoreProductSku, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m merStoreProductSkuDo) Attrs(attrs ...field.AssignExpr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m merStoreProductSkuDo) Assign(attrs ...field.AssignExpr) IMerStoreProductSkuDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m merStoreProductSkuDo) Joins(fields ...field.RelationField) IMerStoreProductSkuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m merStoreProductSkuDo) Preload(fields ...field.RelationField) IMerStoreProductSkuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m merStoreProductSkuDo) FirstOrInit() (*model.MerStoreProductSku, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductSku), nil
	}
}

func (m merStoreProductSkuDo) FirstOrCreate() (*model.MerStoreProductSku, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MerStoreProductSku), nil
	}
}

func (m merStoreProductSkuDo) FindByPage(offset int, limit int) (result []*model.MerStoreProductSku, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m merStoreProductSkuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m merStoreProductSkuDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m merStoreProductSkuDo) Delete(models ...*model.MerStoreProductSku) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *merStoreProductSkuDo) withDO(do gen.Dao) *merStoreProductSkuDo {
	m.DO = *do.(*gen.DO)
	return m
}
