// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEbMerchant = "eb_merchant"

// EbMerchant 商户表
type EbMerchant struct {
	MerID         int32      `gorm:"column:mer_id;type:int unsigned;primaryKey;autoIncrement:true;comment:商户id" json:"mer_id"` // 商户id
	CategoryIds   string     `gorm:"column:category_ids;type:json;not null;comment:商户分类 id" json:"category_ids"`               // 商户分类 id
	MerName       string     `gorm:"column:mer_name;type:varchar(32);not null;comment:商户名称" json:"mer_name"`                   // 商户名称
	RealName      string     `gorm:"column:real_name;type:varchar(32);not null;comment:商户姓名" json:"real_name"`                 // 商户姓名
	MerPhone      string     `gorm:"column:mer_phone;type:varchar(13);not null;comment:商户手机号" json:"mer_phone"`                // 商户手机号
	MerAddress    string     `gorm:"column:mer_address;type:varchar(64);not null;comment:商户地址" json:"mer_address"`             // 商户地址
	MerKeyword    string     `gorm:"column:mer_keyword;type:varchar(64);not null;comment:商户关键字" json:"mer_keyword"`            // 商户关键字
	MerLogo       *string    `gorm:"column:mer_logo;type:varchar(128);comment:商户头像/logo" json:"mer_logo"`                      // 商户头像/logo
	MerBanner     *string    `gorm:"column:mer_banner;type:varchar(128);comment:商户banner图片" json:"mer_banner"`                 // 商户banner图片
	OpeningTime   *time.Time `gorm:"column:opening_time;type:time;comment:营业开始时间" json:"opening_time"`                         // 营业开始时间
	ClosingTime   *time.Time `gorm:"column:closing_time;type:time;comment:营业结束时间" json:"closing_time"`                         // 营业结束时间
	Sales         *int32     `gorm:"column:sales;type:int unsigned;comment:销量" json:"sales"`                                   // 销量
	Mark          string     `gorm:"column:mark;type:varchar(256);not null;comment:商户备注" json:"mark"`                          // 商户备注
	Sort          int32      `gorm:"column:sort;type:int unsigned;not null" json:"sort"`
	Status        bool       `gorm:"column:status;type:tinyint(1);not null;comment:商户是否禁用0锁定,1正常" json:"status"`       // 商户是否禁用0锁定,1正常
	IsDel         int32      `gorm:"column:is_del;type:tinyint unsigned;not null;comment:0未删除1删除" json:"is_del"`       // 0未删除1删除
	MerInfo       string     `gorm:"column:mer_info;type:varchar(256);not null;comment:店铺简介" json:"mer_info"`          // 店铺简介
	ServicePhone  string     `gorm:"column:service_phone;type:varchar(13);not null;comment:店铺电话" json:"service_phone"` // 店铺电话
	CreateAt      time.Time  `gorm:"column:create_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt      time.Time  `gorm:"column:update_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
	MerMoney      float64    `gorm:"column:mer_money;type:decimal(12,2);not null;default:0.00;comment:商户余额" json:"mer_money"` // 商户余额
	BankName      *string    `gorm:"column:bank_name;type:varchar(255);comment:银行名称" json:"bank_name"`                        // 银行名称
	BankCode      *string    `gorm:"column:bank_code;type:varchar(255);comment:银行卡转账信息" json:"bank_code"`                     // 银行卡转账信息
	WalletAddress *string    `gorm:"column:wallet_address;type:varchar(255);comment:钱包地址" json:"wallet_address"`              // 钱包地址
	DeliveryWay   *string    `gorm:"column:delivery_way;type:varchar(50);comment:配送方式" json:"delivery_way"`                   // 配送方式
}

// TableName EbMerchant's table name
func (*EbMerchant) TableName() string {
	return TableNameEbMerchant
}
